Feature/set-Entity
KakaoFunding/back-end pull request #6
Opened 2024-02-05 07:27 UTC by hwan2-99

## #️⃣연관된 이슈

close: #3 

## 📝작업 내용

ERD를 기반으로 각 entity를 모델링하고 entity별로 repository 생성했습니다.

2024-02-05 08:57 UTC, YeaChan05 requested changes
코드에 일부 개선방법에 대한 내용 작성했습니다

전체적으로 @OneToMany 관계의 필드명이 엔티티 자신의 이름을 포함하고 있습니다 

팀 규칙에 `객체명이 중복되는 필드나 메서드 이름은 축약해도 된다`라는 내용도 있기도 하고, 객체명이 중복되는 경우에 getter같은 메서드를 사용할때 혼동이 오기 쉽기 때문에 수정해주시면 감사하겠습니다

ex)

@OneToMany(mappedBy = "productDetail")
    private List<Wish> productDetailWishes;
    ->
    private List<Wish> wishes;

2024-02-05 08:57 UTC, YeaChan05 commented on src/main/java/org/kakaoshare/backend/domain/brand/entity/Brand.java
> +    private Long categoryId;
카테고리가 join column이 아닌것으로 보입니다. 별다른 이유가 있을까요? 
ERD상에는 아직 연관관계를 유지하고 있으니 @ManyToOne관계를 유지하는건 어떨가요?? ☺️

2024-02-05 08:57 UTC, YeaChan05 commented on src/main/java/org/kakaoshare/backend/domain/category/entity/Category.java
> +    @OneToMany(mappedBy = "parent")
자기참조 구조가 재귀적 호출을 하기 떄문에 지연로딩 전략이 필수적으로 보입니다!

2024-02-05 08:57 UTC, YeaChan05 commented on src/main/java/org/kakaoshare/backend/domain/funding/entity/Funding.java
> +    private String status;
상태의 경우에는 열거형 처리도 고려해볼만 하겠군요 😁

2024-02-05 08:57 UTC, YeaChan05 commented on src/main/java/org/kakaoshare/backend/domain/funding/entity/Funding.java
> +    @Column(nullable = false)
생성시간과 수정시간이 중복된거같네요 확인 부탁드립니다!

2024-02-05 08:57 UTC, YeaChan05 commented on src/main/java/org/kakaoshare/backend/domain/funding/entity/Funding.java
> +    private OffsetDateTime expiredAt;
OffsetDateTime을 적용하는 경우에 jpa auditing에 제한이 있는것으로 알고 있습니다
다음 포스팅 참고해주세요 
https://bepoz-study-diary.tistory.com/436

2024-02-05 08:57 UTC, YeaChan05 commented on src/main/java/org/kakaoshare/backend/domain/funding/entity/Funding.java
> +    @Column(nullable = false, precision = 12, scale = 2)
scale 제한으로 금액 제한 주신건가요? 이런 방법도 있네요 🤨
비즈니스 로직상에서의 금액 제한에 실패하는 경우(그럴일은 없겠다만)에 DB에 반영되는걸 막는거같아 보이네요 👏👏

2024-02-05 08:57 UTC, YeaChan05 commented on src/main/java/org/kakaoshare/backend/domain/funding/entity/Funding.java
> +    private List<FundingDetail> fundingFundingDetails;
DDL 따라 작성하다보니 변수명이 이런식으로도 되는군요... DDL 버전 2 만들때 수정할 부분으로 기억해야겠습니다

2024-02-05 08:57 UTC, YeaChan05 commented on src/main/java/org/kakaoshare/backend/domain/brand/entity/Brand.java
> +    @Column
이미지의 URL을 저장히기 때문에 @URL을 사용한 validation도 고려 해볼만한거 같아요!
https://docs.jboss.org/hibernate/stable/validator/api/org/hibernate/validator/constraints/URL.html

2024-02-05 15:20 UTC, kmw2378 reviewed
하시느라 수고 많으셨습니다! `@OneToMany`를 최대한 없애는 건 어떨까요?? 대부분의 경우 단방향 연관관계로 처리할 수 있을 것 같아요!

2024-02-05 15:20 UTC, kmw2378 commented on src/main/java/org/kakaoshare/backend/domain/brand/entity/Brand.java
> +    private Long categoryId;
저도 동의합니다! ORM 수준에서 연관관계는 필요할 것 같습니다!

2024-02-05 15:20 UTC, kmw2378 commented on src/main/java/org/kakaoshare/backend/domain/orders/entity/Orders.java
> +public class Orders extends BaseTimeEntity {
엔티티명은 `Order`로 하고 `@Table(name = "orders")` 을 추가하는 건 어떨까요? 어플리케이션단에서 혼동이 있을 것 같습니다!

2024-02-05 15:20 UTC, kmw2378 commented on src/main/java/org/kakaoshare/backend/domain/orders/entity/Orders.java
> +    private List<Gift> ordersGifts;
필드명에 `orders`를 제거하는건 어떨까요?

2024-02-05 15:20 UTC, kmw2378 commented on src/main/java/org/kakaoshare/backend/domain/payment/entity/Payment.java
> +    private BigDecimal totalPrice;
가격에 `BigDecimal` 이 사용되는데 추후 별도의 VO 객체를 도입하는 것도 좋을 것 같습니다!

2024-02-05 15:20 UTC, kmw2378 commented on src/main/java/org/kakaoshare/backend/domain/product/entity/Product.java
> +    private List<ProductDescriptionPhoto> productProductDescriptionPhotos;
처음엔 의존간계를 단방향으로 설정하고 추후 필요시 양방향으로 설정하는건 어떨까요?

2024-02-06 01:26 UTC, hwan2-99 commented on src/main/java/org/kakaoshare/backend/domain/brand/entity/Brand.java
> +    private Long categoryId;
엇 이부분은 제가 빼먹은것 같아요 수정하겠습니다!

2024-02-06 01:26 UTC, hwan2-99 commented on src/main/java/org/kakaoshare/backend/domain/category/entity/Category.java
> +    @OneToMany(mappedBy = "parent")
수정하겠습니다! 자기참조를 처음만져봐서 그런부분은 생각 못한것 같습니다

2024-02-06 01:27 UTC, hwan2-99 commented on src/main/java/org/kakaoshare/backend/domain/funding/entity/Funding.java
> +    private String status;
이부분은 고민을 많이했었는데 혼자 결정하기 별로일것같아서 별도로 질문하려고 했었습니다 ㅎㅎ

2024-02-06 01:27 UTC, hwan2-99 commented on src/main/java/org/kakaoshare/backend/domain/funding/entity/Funding.java
> +    @Column(nullable = false)
다 뺐다고 생각했는데 빠뜨린부분이있네요.. 수정하겠습니다

2024-02-06 01:27 UTC, hwan2-99 commented on src/main/java/org/kakaoshare/backend/domain/funding/entity/Funding.java
> +    private OffsetDateTime expiredAt;
참고하겠습니다 감사합니다 ㅎ

2024-02-06 01:28 UTC, hwan2-99 commented on src/main/java/org/kakaoshare/backend/domain/funding/entity/Funding.java
> +    private List<FundingDetail> fundingFundingDetails;
변수명도 많이 수정했었는데 이부분은 수정을 안했나보네요.. 수정하겠습니다

2024-02-06 01:30 UTC, hwan2-99 commented on src/main/java/org/kakaoshare/backend/domain/orders/entity/Orders.java
> +public class Orders extends BaseTimeEntity {
그렇게 하는건 좋은데 그럼 다른테이블도 @Table 어노테이션을 붙여주는게 좋을까요?

2024-02-06 01:30 UTC, hwan2-99 commented on src/main/java/org/kakaoshare/backend/domain/orders/entity/Orders.java
> +    private List<Gift> ordersGifts;
수정하겠습니다 ㅎㅎ

2024-02-06 01:58 UTC, hwan2-99 commented on src/main/java/org/kakaoshare/backend/domain/product/entity/Product.java
> +    private List<ProductDescriptionPhoto> productProductDescriptionPhotos;
그렇게 수정하겠습니다 :)

2024-02-06 02:33 UTC, YeaChan05 commented on src/main/java/org/kakaoshare/backend/domain/orders/entity/Orders.java
> +public class Orders extends BaseTimeEntity {
일관성있게 모든 테이블에 테이블명을 직접적으로 명시하는것도 방법일거같아요

저같은 경우에는 order나 user같이 db 예약어를 사용할수도 있을거 같아서 모든 테이블 이름을 복수형으로 하는 편이긴 합니다(옳은 방법인지는 잘 모르겠네요)

2024-02-06 03:03 UTC, YeaChan05 approved these changes

2024-02-06 03:23 UTC, kmw2378 commented on src/main/java/org/kakaoshare/backend/domain/orders/entity/Orders.java
> +public class Orders extends BaseTimeEntity {
말씀하신 일관성이 제일 중요하다 생각해요! `@Table`을 모든 테이블에 명시하고 테이블명을 복수형으로 가져가는 것도 좋을 것 같아요!

2024-02-06 03:26 UTC, kmw2378 approved these changes

2024-02-06 08:42 UTC, YeaChan05 requested changes
전반적으로 Product 테이블과의 관계가 전부 끊어져있는데 이유가 있을까요?

2024-02-06 08:47 UTC, hwan2-99 commented
단방향으로 수정하다가 실수로 상대 엔티티들을 전부 날려버린것 같아요.. 수정하겠습니다

2024-02-07 07:25 UTC, YeaChan05 requested changes

2024-02-07 07:25 UTC, YeaChan05 commented on src/main/java/org/kakaoshare/backend/domain/funding/entity/Funding.java
> +
Product가 없는거같은데 확인 부탁드립니다!

2024-02-08 06:10 UTC, YeaChan05 approved these changes

2024-02-08 06:37 UTC, kmw2378 approved these changes

2024-02-08 06:37 UTC, merged